### PR TITLE
Add Login and Registration Pages with Initial Setup

### PR DESCRIPTION
**Pull request by TeriyakiLemon**
Changes
1. **Update npm dependencies**
   - Updated project dependencies to the latest versions to ensure compatibility and stability.

2. **Add login and registration routes**
   - Added routing logic for the login and registration pages, allowing users to navigate between these pages seamlessly.

3. **Create Login Page Component**
   - Designed and implemented the login page component, which includes form inputs for username and password, as well as buttons for submission and navigation.

4. **Create Registration Page Component**
   - Designed and implemented the registration page component, which includes form inputs for username, email, password, and user type selection (Resident, Property Company, Third Party).

### CODE REVIEW

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Comment by TeriyakiLemon** [comment]
New changes
1.Updateed npm dependencies
-   added ant design icon library to rich our icons

2.Added main page routes
-   Added routing logic for the main page, allowing users to navigate between these pages seamlessly.

3.Created main page
- Designed and implemented the main page layout, which includes simple main page dash board and  side bar to help user switch to different section 

4.Created dash board component
-Simply dashboard layout will be rendered in main page content area.

**Review by shenxingy — APPROVED** [review]

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Review by shenxingy — APPROVED** [review]

**Review by shenxingy — APPROVED** [review]

**Review by shenxingy — APPROVED** [review]

**Review by TeriyakiLemon — COMMENTED** [review]
11111

**Review by shenxingy — APPROVED** [review]

**Review by shenxingy — APPROVED** [review]

**Review by shenxingy — APPROVED** [review]

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Review by TeriyakiLemon — COMMENTED** [review]
1

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Review by shenxingy — APPROVED** [review]

**Review by mshkkhhgy-ychen — APPROVED** [review]

**Comment by shenxingy** [comment]
good

**Comment by shenxingy** [comment]
good

**Pull request closed without merging**
